### ISSUE TITLE
Add a plugin system

### ISSUE THREAD

**Issue by RodolfoSilva** [alex-min/live_view_native_flutter_client#1]
I think the library could have a way to add custom components/actions, like: fl_chart, image_picker, share, copy_to_clipboard, revenue_cat.... Maybe adding a registry of components and actions that can be extensible. I don't know if this would be possible by adding hooks support.

@alex-min What do you expect from hook structure?

**Comment by alex-min** [comment]
I was thinking some kind of plugin system because not everybody would need those components

And you could do some <plugin installed={[:myplugin]} on the server side, to be defined though

**Comment by RodolfoSilva** [comment]
> I was thinking some kind of plugin system because not everybody would need those components
> 
> And you could do some <plugin installed={[:myplugin]} on the server side, to be defined though

This `<plugin installed={[:myplugin]}` solves the problem of custom widgets. So we will need to implement something like hooks to handle custom events, right?

**Comment by alex-min** [comment]
Yes, for now there aren't any hook system implemented
